### ISSUE TITLE
mranderson upgrade

### ISSUE THREAD

**Issue by benedekfazekas** [liquidz/iced-nrepl#14]
mranderson `0.5.3-SNAPSHOT` supposed to support inlining cljfmt `0.7.0`. give it a spin if you have time

**Comment by liquidz** [comment]
@benedekfazekas Thanks for your information!

I tried mranderson `0.5.3-SNAPSHOT` and cljfmt `0.7.0` locally, and it works well.
Thanks!

**Comment by benedekfazekas** [comment]
waiting for cider-nrepl to give it a try and then i might release 3.5.2

**Comment by liquidz** [comment]
@benedekfazekas Do you have any problems about cutting a new release?

**Comment by benedekfazekas** [comment]
nope, just have not gotten to it yet. will do shortly

**Comment by benedekfazekas** [comment]
release done. sorry for the delay

**Comment by liquidz** [comment]
@benedekfazekas thanks!!

**Comment by liquidz** [comment]
Upgraded #15
